version: "3.9"
services:
  chatjava:
    image: ${ENTRY_POINT_IMAGE_NAME}
    ports:
      - ${ENTRY_POINT_PORT}:8080
    volumes:
      - chat-java:/workspace/logs
    networks:
      - chat-java

  setup:
    image: elasticsearch:${ELK_VERSION}
    user: "0"
    command: >
      bash -c '
        echo "Setting kibana_system password";
        until curl -s -X POST -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" http://elastic:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
        echo "Good to go!";
      '
    networks:
      - chat-java

  elastic:
    image: elasticsearch:${ELK_VERSION}
    environment:
      - cluster.name=chatjava-cluster
      - http.port=9200
      - transport.port=9300
      - discovery.type=single-node
      - xpack.security.enabled=true
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - chat-java-elastic:/usr/share/elasticsearch/data
    networks:
      - chat-java

  filebeat:
    image: elastic/filebeat:${ELK_VERSION}
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - chat-java:/workspace/logs
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    networks:
      - chat-java

  kibana:
    image: kibana:${ELK_VERSION}
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
      - XPACK_SECURITY_ENABLED=true
      - SERVERNAME=kibana
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    depends_on:
      setup:
        condition: service_completed_successfully
      elastic:
        condition: service_started
    networks:
      - chat-java

networks:
  chat-java: {}

volumes:
  chat-java: {}
  chat-java-elastic: {}